[build]
  # Build command and output directory
  command = "npm run build"
  publish = ".next"
  
  # Environment variables for build process
  environment = { NODE_VERSION = "18", NEXT_TELEMETRY_DISABLED = "1" }

[build.processing]
  # Skip processing for pre-compressed files
  skip_processing = false

[build.processing.css]
  # Bundle CSS files
  bundle = true
  minify = true

[build.processing.js]
  # Bundle and minify JavaScript
  bundle = true
  minify = true

[build.processing.html]
  # Pretty URLs and minify HTML
  pretty_urls = true
  minify = true

[build.processing.images]
  # Optimize images automatically
  compress = true

# Function configuration for API routes
[functions]
  # Directory for serverless functions (Next.js API routes)
  directory = ".netlify/functions/"
  # Function timeout (max 10 seconds for hobby plan)
  timeout = 10
  # Memory allocation
  memory = 1024

# Edge functions for enhanced performance
[edge_functions]
  directory = ".netlify/edge-functions/"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes with CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Font optimization
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

# Image optimization
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/webp"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/avif"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Environment-specific redirects (example for www to non-www)
[[redirects]]
  from = "https://www.elitizon.com/*"
  to = "https://elitizon.com/:splat"
  status = 301
  force = true

# Old URL redirects for SEO (add your specific redirects here)
[[redirects]]
  from = "/old-contact"
  to = "/contact"
  status = 301

# Form handling for contact form
[[forms]]
  name = "contact"

# Development context for branch deploys
[context.develop]
  command = "npm run build"
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "staging" }

# Production context
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production", NEXT_TELEMETRY_DISABLED = "1" }

# Deploy previews
[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "preview" }

# Plugin configuration for better Next.js support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-lighthouse"
  
  [plugins.inputs.settings]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = "netlify-plugin-sitemap"
  
  [plugins.inputs]
    base_url = "https://elitizon.com"
    pretty_urls = true
    exclude = [
      "/admin/**",
      "/test/**"
    ]
